version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend  
    ports:
      - "3001:3000"
    depends_on:
      - backend
